#!/bin/bash

RESTORE='\033[0m'
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
MAGENTA='\033[35m'
PURPLE='\033[35m'
CYAN='\033[36m'
LIGHTGRAY='\033[37m'
LRED='\033[1;31m'
LGREEN='\033[1;32m'
LYELLOW='\033[1;33m'
LBLUE='\033[1;34m'
LMAGENTA='\033[1;35m'
LPURPLE='\033[1;35m'
LCYAN='\033[1;36m'
WHITE='\033[1;37m'
ORANGE='\033[1;33m'
DARK='\033[1;30m'

OS=`cat /etc/os-release | grep NAME | sed 's/\"//g' | sed 's/.*=//g'`
KERNEL=`uname -r`
RAM=$(echo "$((`cat /proc/meminfo | grep MemTotal | awk '{print $2}'`/1024))")
RAM_USED=$(echo $((`cat /proc/meminfo | grep MemAvailable | awk '{print $2}'`/1024)))
RAM_USED=$(echo $((RAM-RAM_USED)))
UPTIME=`echo $(uptime | awk '{print $3}' | sed 's/,//g' | sed 's/\:/h /g')m`
HOSTNAME=`hostnamectl | head -n 1 | awk '{print $3}'`
USERNAME=`whoami`

echo -e "${BLUE}┏━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
echo -e "${BLUE}┃${RESTORE}   .${ORANGE}~${RESTORE}.   ${BLUE}┃  ${BLUE}$HOSTNAME${RESTORE}@${BLUE}$USERNAME""\t\t"${BLUE}┃
echo -e "${BLUE}┃${RESTORE}   ${DARK}/${ORANGE}V${RESTORE}${DARK}\   ${BLUE}┃  ${PURPLE}os${RESTORE}\t\t$OS""\t"${BLUE}┃
echo -e "${BLUE}┃${RESTORE}  ${DARK}/${WHITE}/ \\\\${DARK}\  ${BLUE}┃  ${PURPLE}uptime${RESTORE}\t$UPTIME""\t\t"${BLUE}┃
echo -e "${BLUE}┃${RESTORE} ${DARK}/${WHITE}(   )${DARK}\ ${BLUE}┃  ${PURPLE}kernel${RESTORE}\t$KERNEL""\t"${BLUE}┃
echo -e "${BLUE}┃${RESTORE}  ${DARK}^${WHITE}\`${ORANGE}~${WHITE}'${DARK}^  ${BLUE}┃  ${PURPLE}ram${RESTORE}\t""$RAM_USED"M / "$RAM"M"\t"${BLUE}┃
echo -e "${BLUE}┗━━━━━━━━━┻━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"
